export const ReviewsDetails = [
  {
    key: 1,
    star: "*****",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Peter",
    reviewDate: "October 10",
  },
  {
    key: 2,
    star: "****",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "John",
    reviewDate: "March 15",
  },
  {
    key: 3,
    star: "*****",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Mike",
    reviewDate: "May 11",
  },
  {
    key: 4,
    star: "**",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Walter",
    reviewDate: "August 26",
  },
  {
    key: 5,
    star: "****",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Bredin",
    reviewDate: "June 13",
  },
  {
    key: 6,
    star: "*****",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Alex",
    reviewDate: "December 6",
  },
  {
    key: 7,
    star: "***",
    heading: "This Heading will be very long",
    msg: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea esse obcaecati enim aspernatur animi cupiditate velit possimus earum neque laboriosam!",
    userName: "Austin",
    reviewDate: "April 16",
  },
];
